#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by NIMA SSH                       #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Nima SSH @KC1993                                   #"
echo -e "# Allah                                         #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# Owner VPS                                     #"
echo -e "# MATMINDAD93                                 #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
